### ISSUE TITLE
Which key mode not adjust its content when centering in on.

### ISSUE THREAD

**Issue by amosbird** [blairdrummond/centering-window-mode#3]
![](https://ptpb.pw/RsxW.jpg)

Can I make it adjust to current width? Or just ignoring centering on which-key-buffer.

**Comment by blairdrummond** [comment]
I'm not quite sure if I understand what you mean. Do you mean you want to prevent the which-key-buffer from being centered?

**Comment by amosbird** [comment]
Sort of. Better to have which-key-buffer adjust to centering mode, i.e. growing its height a little bit.

**Comment by blairdrummond** [comment]
Hmm. I'll look into it. I think that seems possible. Have you integrated this into spacemacs well? If so, if I could see what you've done so far that might help me extend this code to spacemacs more generally.

**Comment by amosbird** [comment]
Well, I just pasted your config into user_config. 😄

**Comment by amosbird** [comment]
Solved by filtering `(equal (buffer-name (window-buffer arg)) " *which-key*")`.
