### ISSUE TITLE
make minibuffer always centered.

### ISSUE THREAD

**Issue by amosbird** [blairdrummond/centering-window-mode#4]
Helm buffers are now centered correctly, which is super cool. However, this makes minibuffer a bit unpleasant.

![](https://ptpb.pw/-GCx.jpg)

Can I make all the content below the helm split bar centered? (including eldoc echo messages)

**Comment by blairdrummond** [comment]
There might be hope here. I think it's almost impossible to get the minibuffer centered, but luckily, I don't think that's the minibuffer that you're looking at. It's a [header-line](https://www.emacswiki.org/emacs/HeaderLine). The code snippet from that link centers the text with that sample. I just need to figure out how to adjust helm to use the header line in the same way as that code snippet does.

**Comment by amosbird** [comment]
fixed in https://github.com/emacs-helm/helm/issues/1690
